### ISSUE TITLE
Unify archives for Gardener source.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/etl-gardener#44]
We currently have archives in two places, and need to unify them.  There are several months of overlapping files.  One option is to use same filenames, but advance the timestamp on the legacy files by 1 second to prevent them colliding with new files.

**Comment by stephen-soltesz** [comment]
Related issue: https://github.com/m-lab/m-lab.github.io/issues/369

**Comment by stephen-soltesz** [comment]
@pboothe is merging m-lab with archive-mlab-oti

Steps to complete:

* copy m-lab (except ndt/2017/{07,08} and execpt switch/) to temporary bucket (legacy-archive-mlab-oti)
* copy archive-mlab-oti (except */2017/05 */2017/06) to legacy-archive-mlab-oti
* remove contents of archive-mlab-oti
* copy legacy-archive-mlab-oti to archive-mlab-oti

**Comment by pboothe** [comment]
Completed steps:
* copy m-lab (except ndt/2017/{07,08} and execpt switch/) to temporary bucket (legacy-archive-mlab-oti)
* copy all of archive-mlab-oti/switch to legacy bucket
* copy archive-mlab-oti data from 2017-07-01 and later to legacy-archive-mlab-oti (except for the switch data, which has already been dealt with)

**Comment by stephen-soltesz** [comment]
copy unembargoed sidestream data from 2016-08 to 2017-05 to legacy-archive-mlab-oti.

**Comment by pboothe** [comment]
So, we have found a potential bug with our internal code. However, that shouldn't stop us from unifying the archives.

First: All data from legacy-archive-mlab-oti will be copied to the archive-mlab-oti bucket. Overwriting all files with clashing names. This copy should close this issue.

After we regenerate all our archives one last time (this time without any embargo in place), we will copy those new tarfiles to m-lab, to legacy-archive-mlab-oti, and then to archive-mlab-oti. This last step is being tracked in a Google-internal bug, because it has to do with Google-internal code that uses tools and systems that may or may not be public knowledge. :(

Hopefully, this is the last time we will ever need to do this, because this is the last step in exfiltrating all M-Lab data from all Google-internal systems.

**Comment by stephen-soltesz** [comment]
Thank you for the update. Please do not close this issue until https://github.com/m-lab/dev-tracker/issues/104 is resolved.
